---
title: 'Why we are here'
author: 'Brian Holland'
date: '2021-11-09'
slug: why-we-are-here
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-11-09T11:26:29-06:00'
featured: yes
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---
```{r}
summary(cars)
```


Why are we here? Well, why am **I** here? That's a pretty important question, and to avoid the "food blog syndrome" with 700 words preceding a 48-word recipe, I think I'll just start with the "how".

I really love listening to podcasts. Driving, doing chores, exercising, I love it.

One day I heard the Planet Money episode titled [Project REDMAP](https://www.npr.org/sections/money/2018/06/01/616216560/episode-845-redmap). In it, they outlined (and [updated on](https://www.npr.org/2020/09/23/916290633/redmap-update) a few years later) the out-in-the-open (and shockingly legal) [Republican campaign](https://en.wikipedia.org/wiki/REDMAP) to win over state legislative houses in order to control the redistricting process. That might not seem that bad, but imagine if a politician could take a surgical blade and cut you and your friends out of your district, and lump you in somewhere completely different. Think about the smartphone you had in 2010, and think about the phone you have now. That's also how much advancement has been made in mapping software (all the while, [the courts refused to rule on gerrymandering](https://www.npr.org/2019/06/27/731847977/supreme-court-rules-partisan-gerrymandering-is-beyond-the-reach-of-federal-court) time and time again). This got me ~~interested~~ angry, so I started reading, first [RatF-cked](https://www.goodreads.com/book/show/26889647-ratf-ked), then [The Big Sort](https://www.goodreads.com/book/show/2569072-the-big-sort), and then found [Dave's Redistricting site](https://davesredistricting.org/
) and the [Princeton Gerrymandering Project](https://gerrymander.princeton.edu/
). And then finally I started googling and found a degree program at Georgetown: Data Science for Public Policy.


The only catch is that Gerrymandering is so easily fixable, it's good to have a more broad focus of study.  One tactic fixes the entire thing: Ranked Choice Voting.  That could be installed with as little as the stroke of a pen, so it's better to have a broader approach.

https://www.goodreads.com/en/book/show/11612989
https://www.youtube.com/watch?v=rStL7niR7gs

> “The major problem—one of the major problems, for there are several—one of the many major problems with governing people is that of whom you get to do it; or rather of who manages to get people to let them do it to them. 
> To summarize: it is a well-known fact that those people who must want to rule people are, ipso facto, those least suited to do it. 
> To summarize the summary: anyone who is capable of getting themselves made President should on no account be allowed to do the job.” 
> 
> Douglas Adams, The Restaurant at the End of the Universe



Next up: Belize.